esphome:
  name: staggkettle
  platform: ESP32
  arduino_version: latest
  board: featheresp32
  includes:
    - StaggESPHome.h
    - StaggKettle.cpp
    - StaggKettle.h

climate:
- platform: custom
  lambda: |-
    auto kettle = new Kettle();
    App.register_component(kettle);
    return {kettle};

  climates:
    - name: "Stagg Kettle"

ota:



# Enable logging
logger:

<<: !include secrets.yaml
