esphome:
  name: staggkettle
  platform: ESP32
  arduino_version: latest
  board: featheresp32
  includes:
    - StaggESPHome.h
    - StaggKettle.cpp
    - StaggKettle.h

climate:
- platform: custom
  lambda: |-
    auto kettle = new Kettle();
    App.register_component(kettle);
    return {kettle};

  climates:
    - name: "Stagg Kettle"


wifi:
  ssid: "Home Wifi"
  password: "robotsftw2406!"

# Enable logging
logger:

mqtt:
  broker: 192.168.1.62
  discovery: true
